### ISSUE TITLE
Auto-format sometimes deletes code

### ISSUE THREAD

**Issue by LukasKalbertodt** [DamnWidget/anaconda_rust#17]
With 0.2.5 of anaconda_rust and this exact code:

``` rust
mod foo ;

// bla

```

When I trigger auto-format, it deletes all the code and leaves me with an empty file. Maybe related to #16

**Comment by DamnWidget** [comment]
Which version of `rustfmt` are you using?

**Comment by LukasKalbertodt** [comment]
```
$ rustfmt -V
0.5.0
```

**Comment by LukasKalbertodt** [comment]
The bug is that you search the formatted file for the first line from the original file. This line might not be in there, because it has been reformatted ([faulty code](https://github.com/DamnWidget/anaconda_rust/blob/08a52f8713b3980d3c5b56b3d0402c669b9bf308/plugin/handlers_rust/commands/rustfmt.py#L89-L98)). Currently I'm running locally with `result = os.linesep.join(buf[2:])`. So far it works just fine, I don't know why it shouldn't...

Also: maybe we shouldn't use the `os.linesep` but the line separator from the original file.

EDIT: my local setup still adds strange empty lines, #16

**Comment by DamnWidget** [comment]
When using display mode, it should just add the filename and a new line to the output but sometimes that is not true (I've read the rustfmt code many times and I didn't found the cause) that is why we have the `_clean_output` method call in there. 

Basically the problem is to use the `display` write mode instead of the `plain` that doesn't add anything from `rustfmt` but ignores `--skip-children` option in `rustfmt` < 0.5.0.

The code in the plugin is not arbitrary random code is there for a reason. It uses `os.linesep` because it maps 1 = 1 what the `rustfmt` code is doing:

``` rust
let style = if config.newline_style == NewlineStyle::Native {
        if cfg!(windows) {
            NewlineStyle::Windows
        } else {
            NewlineStyle::Unix
        }
    } else {
        config.newline_style
    };
```

**Comment by DamnWidget** [comment]
Added commit, please, close if it fix your issue
